-- Tabla detallada de dientes trabajados por solicitud
create table if not exists public.dientes (
  id bigint generated by default as identity primary key,
  solicitud_id bigint not null references public.solicitudes(id) on delete cascade,
  numero integer not null,
  servicio text,
  estado text not null default 'normal',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Indices
create index if not exists idx_dientes_solicitud_id on public.dientes(solicitud_id);
create index if not exists idx_dientes_numero on public.dientes(numero);

-- RLS
alter table public.dientes enable row level security;

drop policy if exists "Los clientes pueden ver dientes de sus solicitudes" on public.dientes;
drop policy if exists "Los clientes pueden crear dientes en sus solicitudes" on public.dientes;
drop policy if exists "Los clientes pueden actualizar dientes de sus solicitudes" on public.dientes;
drop policy if exists "Los clientes pueden eliminar dientes de sus solicitudes" on public.dientes;

create policy "Los clientes pueden ver dientes de sus solicitudes"
  on public.dientes for select
  using (
    exists (
      select 1 from public.solicitudes
      join public.clientes on clientes.id = solicitudes.cliente_id
      where solicitudes.id = dientes.solicitud_id
      and clientes.user_id = auth.uid()
    )
  );

create policy "Los clientes pueden crear dientes en sus solicitudes"
  on public.dientes for insert
  with check (
    exists (
      select 1 from public.solicitudes
      join public.clientes on clientes.id = solicitudes.cliente_id
      where solicitudes.id = dientes.solicitud_id
      and clientes.user_id = auth.uid()
    )
  );

create policy "Los clientes pueden actualizar dientes de sus solicitudes"
  on public.dientes for update
  using (
    exists (
      select 1 from public.solicitudes
      join public.clientes on clientes.id = solicitudes.cliente_id
      where solicitudes.id = dientes.solicitud_id
      and clientes.user_id = auth.uid()
    )
  );

create policy "Los clientes pueden eliminar dientes de sus solicitudes"
  on public.dientes for delete
  using (
    exists (
      select 1 from public.solicitudes
      join public.clientes on clientes.id = solicitudes.cliente_id
      where solicitudes.id = dientes.solicitud_id
      and clientes.user_id = auth.uid()
    )
  );
