create table if not exists public.admins (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null unique,
  nombre text not null,
  email text not null,
  activo boolean default true not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.admins enable row level security;

create policy "Admins can view their own data"
  on public.admins for select
  using (auth.uid() = user_id);

create policy "Admins can update their own data"
  on public.admins for update
  using (auth.uid() = user_id);
