-- Tabla notificaciones para sistema de notificaciones persistente
CREATE TABLE IF NOT EXISTS public.notificaciones (
  id bigint generated by default as identity primary key,
  admin_id bigint,
  cliente_id bigint not null,
  solicitud_id bigint not null,
  conversacion_id bigint not null,
  mensaje_id bigint,
  tipo text not null default 'mensaje',
  titulo text not null,
  contenido text not null,
  vista boolean not null default false,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_notificaciones_admin_id ON public.notificaciones(admin_id);
CREATE INDEX IF NOT EXISTS idx_notificaciones_cliente_id ON public.notificaciones(cliente_id);
CREATE INDEX IF NOT EXISTS idx_notificaciones_solicitud_id ON public.notificaciones(solicitud_id);
CREATE INDEX IF NOT EXISTS idx_notificaciones_conversacion_id ON public.notificaciones(conversacion_id);
CREATE INDEX IF NOT EXISTS idx_notificaciones_vista ON public.notificaciones(vista);
CREATE INDEX IF NOT EXISTS idx_notificaciones_created_at ON public.notificaciones(created_at desc);

-- RLS
ALTER TABLE public.notificaciones ENABLE ROW LEVEL SECURITY;

-- Admins pueden ver todas las notificaciones
CREATE POLICY "notificaciones_admins_select" ON public.notificaciones
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.admins WHERE admins.user_id = auth.uid() AND admins.activo = true
    )
  );

-- Admins pueden insertar notificaciones
CREATE POLICY "notificaciones_admins_insert" ON public.notificaciones
  FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.admins WHERE admins.user_id = auth.uid() AND admins.activo = true
    )
  );

-- Admins pueden actualizar notificaciones (marcar vista)
CREATE POLICY "notificaciones_admins_update" ON public.notificaciones
  FOR UPDATE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.admins WHERE admins.user_id = auth.uid() AND admins.activo = true
    )
  );

-- Trigger para updated_at
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS handle_notificaciones_updated_at ON public.notificaciones;
CREATE TRIGGER handle_notificaciones_updated_at
  BEFORE UPDATE ON public.notificaciones
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- Realtime
alter publication supabase_realtime add table notificaciones;
