-- Tabla notificaciones para sistema de notificaciones persistente
CREATE TABLE IF NOT EXISTS public.notificaciones (
  id bigint generated by default as identity primary key,
  admin_id bigint,
  cliente_id bigint not null,
  solicitud_id bigint not null,
  conversacion_id bigint not null,
  mensaje_id bigint,
  tipo text not null default 'mensaje',
  titulo text not null,
  contenido text not null,
  vista boolean not null default false,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_notificaciones_admin_id ON public.notificaciones(admin_id);
CREATE INDEX IF NOT EXISTS idx_notificaciones_cliente_id ON public.notificaciones(cliente_id);
CREATE INDEX IF NOT EXISTS idx_notificaciones_solicitud_id ON public.notificaciones(solicitud_id);
CREATE INDEX IF NOT EXISTS idx_notificaciones_conversacion_id ON public.notificaciones(conversacion_id);
CREATE INDEX IF NOT EXISTS idx_notificaciones_vista ON public.notificaciones(vista);
CREATE INDEX IF NOT EXISTS idx_notificaciones_created_at ON public.notificaciones(created_at desc);

-- RLS
ALTER TABLE public.notificaciones ENABLE ROW LEVEL SECURITY;

-- Admins pueden ver sus propias notificaciones
CREATE POLICY "notificaciones_admins_select" ON public.notificaciones
  FOR SELECT TO authenticated
  USING (
    admin_id IN (
      SELECT id FROM public.admins WHERE admins.user_id = auth.uid() AND admins.activo = true
    )
  );

-- Admins pueden insertar notificaciones
CREATE POLICY "notificaciones_admins_insert" ON public.notificaciones
  FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.admins WHERE admins.user_id = auth.uid() AND admins.activo = true
    )
  );

-- Admins pueden actualizar sus propias notificaciones (marcar vista)
CREATE POLICY "notificaciones_admins_update" ON public.notificaciones
  FOR UPDATE TO authenticated
  USING (
    admin_id IN (
      SELECT id FROM public.admins WHERE admins.user_id = auth.uid() AND admins.activo = true
    )
  );

-- Clientes pueden ver sus propias notificaciones
CREATE POLICY "notificaciones_clientes_select" ON public.notificaciones
  FOR SELECT TO authenticated
  USING (
    cliente_id IN (
      SELECT id FROM public.clientes WHERE clientes.user_id = auth.uid()
    )
  );

-- Clientes pueden actualizar (marcar como vista) sus propias notificaciones
CREATE POLICY "notificaciones_clientes_update" ON public.notificaciones
  FOR UPDATE TO authenticated
  USING (
    cliente_id IN (
      SELECT id FROM public.clientes WHERE clientes.user_id = auth.uid()
    )
  );

-- Permitir que el trigger inserte notificaciones (usando service_role implícito)
-- Nota: Los triggers de Postgres tienen privilegios de service_role por defecto

-- Trigger para updated_at
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS handle_notificaciones_updated_at ON public.notificaciones;
CREATE TRIGGER handle_notificaciones_updated_at
  BEFORE UPDATE ON public.notificaciones
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- Trigger para crear notificación cuando admin envía mensaje
CREATE OR REPLACE FUNCTION public.crear_notificacion_mensaje()
RETURNS TRIGGER AS $$
DECLARE
  conversacion_registro record;
  v_cliente_nombre text;
  v_servicio text;
BEGIN
  -- Obtener datos de la conversación
  SELECT solicitud_id, cliente_id, admin_id INTO conversacion_registro
  FROM public.conversaciones WHERE id = NEW.conversacion_id;

  -- Si el remitente es admin, notificar al cliente
  IF NEW.remitente = 'admin' AND conversacion_registro.cliente_id IS NOT NULL THEN
    INSERT INTO public.notificaciones (
      cliente_id,
      solicitud_id,
      conversacion_id,
      mensaje_id,
      tipo,
      titulo,
      contenido,
      vista
    ) VALUES (
      conversacion_registro.cliente_id,
      conversacion_registro.solicitud_id,
      NEW.conversacion_id,
      NEW.id,
      'nuevo_mensaje',
      'Nuevo mensaje',
      'Tienes un nuevo mensaje de Arte Cerámico',
      false
    );
  END IF;

  -- Si el remitente es cliente, notificar a todos los admins
  IF NEW.remitente = 'cliente' THEN
    SELECT c.nombre, s.servicio INTO v_cliente_nombre, v_servicio
    FROM public.solicitudes s
    JOIN public.clientes c ON c.id = s.cliente_id
    WHERE s.id = conversacion_registro.solicitud_id;

    INSERT INTO public.notificaciones
    (
      admin_id,
      cliente_id,
      solicitud_id,
      conversacion_id,
      mensaje_id,
      tipo,
      titulo,
      contenido,
      vista
    )
    select
      a.id,
      conversacion_registro.cliente_id,
      conversacion_registro.solicitud_id,
      NEW.conversacion_id,
      NEW.id,
      'nuevo_mensaje',
      'Respuesta de cliente',
      'Un cliente ha respondido en una conversación',
      false
    from admins a
    where a.activo = true;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trigger_crear_notificacion_mensaje ON public.mensajes;
CREATE TRIGGER trigger_crear_notificacion_mensaje
  AFTER INSERT ON public.mensajes
  FOR EACH ROW EXECUTE FUNCTION public.crear_notificacion_mensaje();

-- Trigger para crear notificación cuando cliente envía mensaje en mensajes_solicitud
CREATE OR REPLACE FUNCTION public.crear_notificacion_solicitud_cliente()
RETURNS TRIGGER AS $$
DECLARE
  v_cliente_id bigint;
  v_cliente_nombre text;
  v_servicio text;
BEGIN
  -- Obtener datos de la solicitud y cliente
  SELECT s.cliente_id, c.nombre, s.servicio INTO v_cliente_id, v_cliente_nombre, v_servicio
  FROM public.solicitudes s
  JOIN public.clientes c ON c.id = s.cliente_id
  WHERE s.id = NEW.solicitud_id;

  -- Si el autor es cliente, notificar a todos los admins
  IF NEW.autor = 'cliente' THEN
    INSERT INTO public.notificaciones
    (
      admin_id,
      cliente_id,
      solicitud_id,
      conversacion_id,
      mensaje_id,
      tipo,
      titulo,
      contenido,
      vista
    )
    select
      a.id,
      v_cliente_id,
      NEW.solicitud_id,
      NULL,
      NEW.id,
      'mensaje',
      'Nuevo mensaje',
      'El cliente "' || v_cliente_nombre || '" envió un mensaje sobre "' || v_servicio || '".',
      false
    from admins a
    where a.activo = true;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trigger_crear_notificacion_solicitud_cliente ON public.mensajes_solicitud;
CREATE TRIGGER trigger_crear_notificacion_solicitud_cliente
  AFTER INSERT ON public.mensajes_solicitud
  FOR EACH ROW EXECUTE FUNCTION public.crear_notificacion_solicitud_cliente();

-- Realtime
alter publication supabase_realtime add table notificaciones;
