-- Tabla de solicitudes de servicio
create table if not exists public.solicitudes (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references public.clientes(id) on delete cascade,
  servicio text not null,
  observaciones text,
  urls_documentos text[] default '{}',
  estado text default 'pendiente',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tabla de servicios/productos asociados a solicitudes
create table if not exists public.servicios (
  id bigint generated by default as identity primary key,
  solicitud_id bigint not null references public.solicitudes(id) on delete cascade,
  nombre text not null,
  descripcion text,
  precio numeric(10, 2),
  cantidad integer default 1,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Indices para mejorar rendimiento
create index if not exists idx_solicitudes_cliente_id on public.solicitudes(cliente_id);
create index if not exists idx_solicitudes_estado on public.solicitudes(estado);
create index if not exists idx_servicios_solicitud_id on public.servicios(solicitud_id);

-- Habilitar RLS
alter table public.solicitudes enable row level security;
alter table public.servicios enable row level security;

-- Eliminar políticas existentes para evitar conflictos
drop policy if exists "Los clientes pueden ver sus propias solicitudes" on public.solicitudes;
drop policy if exists "Los clientes pueden crear sus propias solicitudes" on public.solicitudes;
drop policy if exists "Los clientes pueden actualizar sus propias solicitudes" on public.solicitudes;
drop policy if exists "Los clientes pueden eliminar sus propias solicitudes" on public.solicitudes;
drop policy if exists "Los clientes pueden ver servicios de sus solicitudes" on public.servicios;
drop policy if exists "Los clientes pueden crear servicios en sus solicitudes" on public.servicios;
drop policy if exists "Los clientes pueden actualizar servicios de sus solicitudes" on public.servicios;
drop policy if exists "Los clientes pueden eliminar servicios de sus solicitudes" on public.servicios;

-- Políticas RLS para solicitudes
create policy "Los clientes pueden ver sus propias solicitudes"
  on public.solicitudes for select
  using (
    exists (
      select 1 from public.clientes
      where clientes.id = solicitudes.cliente_id
      and clientes.user_id = auth.uid()
    )
  );

create policy "Los clientes pueden crear sus propias solicitudes"
  on public.solicitudes for insert
  with check (
    exists (
      select 1 from public.clientes
      where clientes.id = solicitudes.cliente_id
      and clientes.user_id = auth.uid()
    )
  );

create policy "Los clientes pueden actualizar sus propias solicitudes"
  on public.solicitudes for update
  using (
    exists (
      select 1 from public.clientes
      where clientes.id = solicitudes.cliente_id
      and clientes.user_id = auth.uid()
    )
  );

create policy "Los clientes pueden eliminar sus propias solicitudes"
  on public.solicitudes for delete
  using (
    exists (
      select 1 from public.clientes
      where clientes.id = solicitudes.cliente_id
      and clientes.user_id = auth.uid()
    )
  );

-- Políticas RLS para servicios
create policy "Los clientes pueden ver servicios de sus solicitudes"
  on public.servicios for select
  using (
    exists (
      select 1 from public.solicitudes
      join public.clientes on clientes.id = solicitudes.cliente_id
      where solicitudes.id = servicios.solicitud_id
      and clientes.user_id = auth.uid()
    )
  );

create policy "Los clientes pueden crear servicios en sus solicitudes"
  on public.servicios for insert
  with check (
    exists (
      select 1 from public.solicitudes
      join public.clientes on clientes.id = solicitudes.cliente_id
      where solicitudes.id = servicios.solicitud_id
      and clientes.user_id = auth.uid()
    )
  );

create policy "Los clientes pueden actualizar servicios de sus solicitudes"
  on public.servicios for update
  using (
    exists (
      select 1 from public.solicitudes
      join public.clientes on clientes.id = solicitudes.cliente_id
      where solicitudes.id = servicios.solicitud_id
      and clientes.user_id = auth.uid()
    )
  );

create policy "Los clientes pueden eliminar servicios de sus solicitudes"
  on public.servicios for delete
  using (
    exists (
      select 1 from public.solicitudes
      join public.clientes on clientes.id = solicitudes.cliente_id
      where solicitudes.id = servicios.solicitud_id
      and clientes.user_id = auth.uid()
    )
  );