-- Tabla para encuestas de post-adaptación
CREATE TABLE IF NOT EXISTS public.encuestas_postadaptacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  solicitud_id BIGINT NOT NULL REFERENCES public.solicitudes(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  paciente TEXT NOT NULL,
  evaluaciones TEXT[] NOT NULL DEFAULT '{}',
  opinion TEXT NOT NULL,
  nombre_profesional TEXT NOT NULL,
  fecha_entrega TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Tabla para buzón de quejas/reclamos/sugerencias/felicitaciones
CREATE TABLE IF NOT EXISTS public.buzon_quejas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  solicitud_id BIGINT NOT NULL REFERENCES public.solicitudes(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  tipo TEXT NOT NULL,
  descripcion TEXT NOT NULL,
  notificacion TEXT[] NOT NULL DEFAULT '{}',
  nombre_completo TEXT NOT NULL,
  correo_electronico TEXT NOT NULL,
  comentarios_adicionales TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Índices para búsquedas frecuentes
CREATE INDEX IF NOT EXISTS idx_encuestas_postadaptacion_solicitud_id ON public.encuestas_postadaptacion(solicitud_id);
CREATE INDEX IF NOT EXISTS idx_buzon_quejas_solicitud_id ON public.buzon_quejas(solicitud_id);

-- Trigger para actualizar updated_at
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_encuestas_postadaptacion_updated_at ON public.encuestas_postadaptacion;
CREATE TRIGGER update_encuestas_postadaptacion_updated_at
  BEFORE UPDATE ON public.encuestas_postadaptacion
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_buzon_quejas_updated_at ON public.buzon_quejas;
CREATE TRIGGER update_buzon_quejas_updated_at
  BEFORE UPDATE ON public.buzon_quejas
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Habilitar RLS
ALTER TABLE public.encuestas_postadaptacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.buzon_quejas ENABLE ROW LEVEL SECURITY;

-- Políticas RLS para encuestas_postadaptacion
CREATE POLICY "Allow public read encuestas_postadaptacion" ON public.encuestas_postadaptacion
  FOR SELECT USING (true);

CREATE POLICY "Allow public insert encuestas_postadaptacion" ON public.encuestas_postadaptacion
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public update encuestas_postadaptacion" ON public.encuestas_postadaptacion
  FOR UPDATE USING (true);

-- Políticas RLS para buzon_quejas
CREATE POLICY "Allow public read buzon_quejas" ON public.buzon_quejas
  FOR SELECT USING (true);

CREATE POLICY "Allow public insert buzon_quejas" ON public.buzon_quejas
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public update buzon_quejas" ON public.buzon_quejas
  FOR UPDATE USING (true);
