-- Tabla de plantillas de fases (maestro de fases disponibles)
create table if not exists public.fases_template (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  descripcion text,
  orden integer default 0 not null,
  activa boolean default true not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tabla de asignación de fases a empleados
create table if not exists public.empleado_fases (
  id bigint generated by default as identity primary key,
  empleado_id bigint references public.empleados on delete cascade not null,
  fase_template_id bigint references public.fases_template on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (empleado_id, fase_template_id)
);

alter table public.fases_template enable row level security;
alter table public.empleado_fases enable row level security;

-- Políticas para fases_template
create policy "Anyone can view active phase templates"
  on public.fases_template for select
  using (activa = true);

create policy "Admins can manage phase templates"
  on public.fases_template for all
  using (
    exists (
      select 1 from public.admins where user_id = auth.uid() and activo = true
    )
  );

-- Políticas para empleado_fases
create policy "Employees can view their assigned phases"
  on public.empleado_fases for select
  using (
    empleado_id in (
      select id from public.empleados where user_id = auth.uid()
    )
  );

create policy "Admins can manage employee phase assignments"
  on public.empleado_fases for all
  using (
    exists (
      select 1 from public.admins where user_id = auth.uid() and activo = true
    )
  );

-- Insertar fases del proceso de fabricación (basadas en FASES_PROCESO)
insert into public.fases_template (nombre, descripcion, orden) values
  ('LIMPIEZA Y DESINFECCION DE ENTRADA', 'Limpieza y desinfección inicial de piezas entrantes', 1),
  ('VACEADO Y PREPARACION MODELOS', 'Vaciado y preparación de modelos de trabajo', 2),
  ('PLATO BASE Y RODETE', 'Creación de plato base y rodete', 3),
  ('ESCANEO Y DISEÑO', 'Escaneo digital y diseño CAD', 4),
  ('DISEÑO DE MODELO 3D', 'Diseño del modelo en 3D', 5),
  ('LIBERADO Y PULIDO DE META EXTERNALIZADO', 'Liberado y pulido de metal externalizado', 6),
  ('CONTROL DE CALIDAD DE PROCESO 1', 'Primer control de calidad del proceso', 7),
  ('IMPRESION RESINA', 'Impresión 3D en resina', 8),
  ('FRESADO ZR-DSL-PMMA', 'Fresado de zirconio, disilicato o PMMA', 9),
  ('FRESADO CERA', 'Fresado en cera', 10),
  ('ENCERADO MANUAL', 'Encerado manual de estructuras', 11),
  ('SINTERIZADO', 'Proceso de sinterizado', 12),
  ('IMPRESION 3D', 'Impresión 3D general', 13),
  ('DISEÑO DE BARRA', 'Diseño de barra para estructuras', 14),
  ('ENFILADO', 'Proceso de enfilado', 15),
  ('CONTROL CALIDAD DE PROCESO 2', 'Segundo control de calidad del proceso', 16),
  ('PULIDO DE METAL Y RESINAS', 'Pulido de metal y resinas', 17),
  ('MICROFRESADO', 'Microfresado de precisión', 18),
  ('FRESADO MONTURA', 'Fresado de monturas', 19),
  ('REVESTIR + DESENCERAR + INYECTAR', 'Revestido, desencerado e inyección', 20),
  ('LIBERADO Y PULIDO LIBRE DE METAL', 'Liberado y pulido libre de metal', 21),
  ('MAQUILLAJE Y CERAMICA', 'Maquillaje y aplicación de cerámica', 22),
  ('CONTROL DE CALIDAD LIBERACION', 'Control de calidad para liberación', 23),
  ('LIMPIEZA Y DESINFECCION DE DISPOSITIVO TERMINADO', 'Limpieza y desinfección final del dispositivo', 24)
on conflict (nombre) do nothing;