create table if not exists public.empleados (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null unique,
  nombre text not null,
  email text not null,
  rol text not null default 'empleado',
  activo boolean default true not null,
  creado_por uuid references auth.users on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.empleados enable row level security;

create policy "Empleados can view their own data"
  on public.empleados for select
  using (auth.uid() = user_id);

create policy "Empleados can update their own data"
  on public.empleados for update
  using (auth.uid() = user_id);

create policy "Admins can manage all empleados"
  on public.empleados for all
  using (
    exists (
      select 1 from public.admins where user_id = auth.uid() and activo = true
    )
  );